version: '3.6'
services:
  database:
    image: postgres:13
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=user123456
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=test
    container_name: 'postgres-for-testing'
    ports:
      - '54320:5432'
    tmpfs: /tmp/lib/postgresql/data
